projsite/golfers/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^(?P<course_id>[0-9]+)/', views.course, name = 'course'),

	url(r'^adduser/', views.adduser, name = 'adduser'),
	url(r'^addcourse/', views.addcourse, name = 'addcourse'),

	url(r'^$', views.index, name = 'index'),
]

projsite/projsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'projsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^golfers/', include('golfers.urls', namespace ="golfers")),
    url(r'^$', include('golfers.urls', namespace="golfers")),
]

projsite/golfers/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator


class Golfer(models.Model):
	first_name = models.CharField(max_length = 30)
	last_name = 	models.CharField(max_length = 30)
	age = 		models.IntegerField(default = 30, validators = [MinValueValidator(1),])

	def __unicode__(self):
		return self.first_name + " " + self.last_name

class Course(models.Model):
	course_name = 	models.CharField(max_length = 60)
	par = 			models.IntegerField(default = 72)
	city = 			models.CharField(max_length = 30)
	state = 		models.CharField(max_length = 2)

	def __unicode__(self):
		return self.course_name

	
class Round(models.Model):
	golfer = 	models.ForeignKey('Golfer')
	course = 	models.ForeignKey('Course')
	round_date= models.DateTimeField('date published')
	score = 	models.IntegerField(default = 72, validators = [MinValueValidator(50),])
	gir = 		models.IntegerField(default = 12, validators = [MinValueValidator(0), MaxValueValidator(18)])
	putts = 	models.IntegerField(default = 36, validators = [MinValueValidator(0),])
	fairways = 	models.IntegerField(default = 12, validators = [MinValueValidator(0), MaxValueValidator(18)])

	def __unicode__(self):
		return unicode(self.golfer) + " " + \
			unicode(self.course)  + " " + \
			self.round_date.strftime('%x ') +  "" + \
			unicode(self.score)

projsite/projsite/golfers/models.py
from django.db import models

# Create your models here.

projsite/projsite/polls/models.py
from django.db import models

# Create your models here.

projsite/golfers/forms.py
from django import forms
from django.forms import ModelForm
from .models import Course, Golfer, Round
from datetime import date

class NameForm(forms.Form):
	your_name = forms.CharField(label = 'Your name', max_length=100)


class GolferModelForm(forms.ModelForm):
	class Meta:
		model = Golfer
		fields ='__all__'

#we might only allow the admin to add courses
class CourseModelForm(forms.ModelForm):
	class Meta:
		model = Course
		fields = ['course_name', 'par', 'city', 'state',]

class RoundModelForm(forms.ModelForm):
	class Meta:
		model = Round
		round_date = forms.DateField(label = 'date published', input_formats = ['%Y-%m-%d %H:%M'], initial=date.today)
		fields = '__all__'

class CourseSelectForm(forms.ModelForm):
	class Meta:
		model = Round
		fields = ['course',]

projsite/golfers/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.forms.models import inlineformset_factory
from django.core.urlresolvers import reverse

from .forms import NameForm,GolferModelForm,CourseModelForm,RoundModelForm, CourseSelectForm

from .models import Golfer, Round,Course

def index(request):
	golfer_list = Golfer.objects.order_by('-last_name')
	round_list = Round.objects.order_by('-score').reverse()
	course_list = Course.objects.order_by('-course_name')

	#handle adding round
	if request.method == 'POST':
		roundModelForm = RoundModelForm(request.POST)		
		if roundModelForm.is_valid():
			#need to redirect to their course page
			roundModelForm.save()
			courseid = roundModelForm.cleaned_data['course'].id
			return HttpResponseRedirect(reverse('golfers:course', args=(courseid,)))
		
		courseSelectForm = CourseSelectForm(request.POST)
		if courseSelectForm.is_valid():
			courseid = courseSelectForm.cleaned_data['course'].id
			return HttpResponseRedirect(reverse('golfers:course', args=(courseid,)))

	else:
		roundModelForm = RoundModelForm()
		courseSelectForm = CourseSelectForm()
	context = {'golfer_list' : golfer_list, 
				'round_list' : round_list, 
				'course_list' : course_list,
				'roundModelForm' : roundModelForm,
				'courseSelectForm' : CourseSelectForm}
	
	return render(request, 'golfers/index.html', context)

#Very similiar to index but takes a course_id argument
def course(request, course_id):
	golfer_list = Golfer.objects.order_by('-last_name')
	localcourse = Course.objects.filter(pk = course_id)
	round_list = Round.objects.filter(course = localcourse)
	round_list = round_list.order_by('-score').reverse()

	if request.method == 'POST':
		roundModelForm = RoundModelForm(request.POST)
		if roundModelForm.is_valid():
			#need to redirect to their course page
			roundModelForm.save()
			courseid = roundModelForm.cleaned_data['course'].id
			return HttpResponseRedirect(reverse('golfers:course', args=(courseid,)))
		
		courseSelectForm = CourseSelectForm(request.POST)
		if courseSelectForm.is_valid():
			courseid = courseSelectForm.cleaned_data['course'].id
			return HttpResponseRedirect(reverse('golfers:course', args=(courseid,)))
	else:
		roundModelForm = RoundModelForm()
		courseSelectForm = CourseSelectForm()

	context = {'round_list' : round_list,
				'golfer_list' : golfer_list,
				'course_list' : localcourse,
				'roundModelForm' : roundModelForm,
				'courseSelectForm': CourseSelectForm}
	# return HttpResponse("HI: " + str(round_list[0]))
	return 	render(request, 'golfers/index.html', context)


def adduser(request):
	if request.method == 'POST':
		golferModelForm = GolferModelForm(request.POST)
		if golferModelForm.is_valid():
			golferModelForm.save()

			return HttpResponseRedirect(reverse('golfers:index'))
	else:
		golferModelForm = GolferModelForm()
	return render(request, 'golfers/form.html', {'golferModelForm' : golferModelForm})

def addcourse(request):
	if request.method == 'POST':
		courseModelForm = CourseModelForm(request.POST)
		if courseModelForm.is_valid():
			courseModelForm.save()
			name = courseModelForm.cleaned_data['course_name']
			course = Course.objects.get(course_name = name)
			return HttpResponseRedirect(reverse('golfers:course', args = (course.id,)))
	else:
		courseModelForm = CourseModelForm()
	return render(request, 'golfers/form.html', {'courseModelForm' : courseModelForm})



def create(request):
	if request.method == 'POST':
		courseModelForm = CourseModelForm(request.POST)
		golferModelForm = GolferModelForm(request.POST)
		roundModelForm = RoundModelForm(request.POST)
		if roundModelForm.is_valid() and golferModelForm.is_valid() and roundModelForm.is_valid():
			return HttpResponse('Thanks')
	else:
		roundModelForm = RoundModelForm()
		golferModelForm = GolferModelForm()
		courseModelForm = CourseModelForm()
	return render(request, 'golfers/create.html', {'roundModelForm': roundModelForm,
				 'courseModelForm': courseModelForm, 'golferModelForm' : golferModelForm})

projsite/projsite/golfers/views.py
# Create your views here.

projsite/projsite/polls/views.py
# Create your views here.

projsite/golfers/templates/golfers/form.html
<!DOCTYPE html>
<html>
<head>
	<title>GScore | Home</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	{%load staticfiles%}

	<style type="text/css">
		body {background-image: url("http://i.imgur.com/hRdn4Kb.jpg");}
		#infoDiv {background-color: #ffffff; opacity: 0.85}
		#leaderDiv {background-color: #ffffff; opacity: 0.95}}
	</style>
</head>


{%if golferModelForm %}
<div class="container" id="infoDiv">
	<h2>Please enter your round information below:</h2>		
	<form action={% url 'golfers:adduser' %} method="post">
		{% csrf_token %}
		{{ golferModelForm }}
		<input type = "submit" value = "Submit" />
</form>
</div>


{%elif courseModelForm %}
<div class="container" id="infoDiv">
	<h2>Please enter your course information below:</h2>		
	<form action={% url 'golfers:addcourse' %} method="post">
		{% csrf_token %}
		{{ courseModelForm }}
		<input type = "submit" value = "Submit" />
</form>
</div>

{%else%}
<p>Could not load form</p>
{%endif%}

</html>

projsite/golfers/templates/golfers/golfers.html
<!DOCTYPE html>
<html>
<head>
	<title>GScore | Home</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	{%load staticfiles%}

	<style type="text/css">
		#infoDiv {background-color: #ffffff; opacity: 0.85}
	</style>
</head>

	{%if round_list %}
	<table class="table table-striped">
		<thead>
      	<tr>
         	<th>Firstname</th>
         	<th>Lastname</th>
         	<th>Age</th>
         	<th>Score</th>
         	<th>Putts</th>
         	<th>GIR</th>
         	<th>Fairways</th>
         	<th>Date</th>
      	</tr>
		</thead>
    	<tbody>
    	
    	{% for round in round_list %}	
      	<tr>
         	<td>{{round.golfer.first_name}}</td>
        		<td>{{round.golfer.last_name}}</td>
        		<td>{{round.golfer.age}}</td>
        		<td>{{round.score}}</td>
        		<td>{{round.putts}}</td>
        		<td>{{round.gir}}</td>
        		<td>{{round.fairways}}</td>
        		<td>{{round.round_date}}</td>
        		<td>{{round.course.course_name}}</td>
      	</tr>
      	{% endfor %}  	
		</tbody>
	</table>
	{%else%}
	<h2>No rounds have currently been recorded at this course.</h2>
	{%endif%}

projsite/golfers/templates/golfers/index.html
<!DOCTYPE html>
<html>
<head>
	<title>GScore | Home</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	{%load staticfiles%}

	<style type="text/css">
		body {background-image: url("http://i.imgur.com/hRdn4Kb.jpg");}
		#infoDiv {background-color: #ffffff; opacity: 0.85}
		#leaderDiv {background-color: #ffffff; opacity: 0.95}
		#courseDiv {background-color: #ffffff; opacity: 0.90}
	</style>
</head>
<link rel ="stylesheet" type = "text/css" href ="{%static 'golfers/style.css'%}" />




{% if golfer_list and course_list%}
<body>
	<div class="container" id="introDiv">
	<h1>Welcome to GScore: The community golf score leader board!</h1>	
	</div>
	
	<br><br>
	<!--Round Form Data-->
	<div class="container" id="infoDiv">
		<h2>Please enter your round information below:</h2>		
		<form action={% url 'golfers:index' %} method="post">
			{% csrf_token %}
			{{ roundModelForm }}
			<input type = "submit" value = "Submit" />
	</form>
	<p>To enter a new user click <a href="{% url 'golfers:adduser'%}">here</a></p>
	<p>To enter a new course click <a href="{% url 'golfers:addcourse'%}">here</a></p>
	</div>


<div class = "container" id = "courseDiv">
	<h2>Select an individual course to view scores from:</h2>
	<form action={% url 'golfers:index' %} method="post">
		{% csrf_token %}
		{{ courseSelectForm }}
		<input type = "submit" value = "Submit" />
	</form>
</div>

<br><br>
	<!-- End user input -->

	<!-- Begin leaderboard -->
<div class="container" id="leaderDiv">
	{%if course_list|length > 1 %}
	<h2>Welmcome to the Overall Leaderboard</h2>
	{%else%}
	{%for course in course_list%}
	<h2>{{course.course_name}}</h2>
	<p>Located in: {{course.city}}, {{course.state}}</p>
	<p>Par for the course is: {{course.par}}</p> 
	
	{%endfor%}
	{%endif%}

	{%if round_list %}
	<table class="table table-striped">
		<thead>
      	<tr>
         	<th>Firstname</th>
         	<th>Lastname</th>
         	<th>Age</th>
         	<th>Score</th>
         	<th>Putts</th>
         	<th>GIR</th>
         	<th>Fairways</th>
         	<th>Date</th>
      	</tr>
		</thead>
    	<tbody>
    	
    	{% for round in round_list %}	
      	<tr>
         	<td>{{round.golfer.first_name}}</td>
        		<td>{{round.golfer.last_name}}</td>
        		<td>{{round.golfer.age}}</td>
        		<td>{{round.score}}</td>
        		<td>{{round.putts}}</td>
        		<td>{{round.gir}}</td>
        		<td>{{round.fairways}}</td>
        		<td>{{round.round_date}}</td>
      	</tr>
      	{% endfor %}
  	
		</tbody>
	</table>
	{%else%}
	<h2>No rounds have currently been recorded at this course.</h2>
	{%endif%}


</div>

<br><br>
<br><br>

	<!-- End leaderboard -->

</body>
{%endif %}
</html>